### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by yashsalvi** [pararell/eshop_mean#3]
Can you guide me for running the server on local machine

**Comment by pararell** [comment]
Hi @yashsalvi , what is problem at your side?
You can find info here https://github.com/pararell/eshop_mean/blob/master/README.md
and here http://miroslavsmrtic.sk/blog/build_eshop_template_with_mean_stack_and_typescript___dev_and_prod_build
http://miroslavsmrtic.sk/blog/build_eshop_template_with_mean_stack_and_typescript___set_environment_variables_and_build_it

For the server you need mongoDB, that setting depends on your operating system. Or you can use https://account.mongodb.com/ and create free sandbox DB for dev purpose

**Comment by yashsalvi** [comment]
I will try to use the sandboxDB right now.
I'm not getting how to use the local mongoDB setup which has a URI in .env file
I'm not able to get that URI.

**Comment by pararell** [comment]
It depends on the operating system, it is probably easier setup in Ubuntu that in Windows. Anyway, try mongodb.com sandbox DB and you will get link from there and that you can use in .env
MONGO_URI="mongodb+srv://username:password@yourclusterurl.mongodb.net/yourDBname?retryWrites=true&w=majority"
