### ISSUE TITLE
Can't run a working clone

### ISSUE THREAD

**Issue by abhinit21** [pararell/eshop_mean#5]
TO Recreate ERROR:

Clone repo

`npm install`

`npm run start`

```
Error: Cannot find module 'C:\Users\KARTHIKEYA\UN NAMMED\Visual Studio Projects\Web Dev\eshop_mean\dist\eshop\server\main.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by abhinit21** [comment]
@pararell 
My understanding is that the dist root --path
but I can't know how and what to define it

**Comment by pararell** [comment]
Hi, please check **package.json** first. If you want to run server, it is **npm run build:server** and **npm run start:server** - should be PORT 4000 - set PORT and DB (MONGO_URI) in **.env**. For the client **npm run start:client** - it will be on PORT 4200. For SSR it is **npm run build:ssr** and **npm run start**.
